### ISSUE TITLE
Please add Tough As Nails support

### ISSUE THREAD

**Issue by Zaakjin** [Darkhax-Minecraft/Thirsty-Bottles#2]
[Tough As Nails](https://minecraft.curseforge.com/projects/tough-as-nails?gameCategorySlug=mc-mods&projectID=246391)

**Comment by ImadethisjustforNVIDIAFleX** [comment]
please

**Comment by DevOpDan** [comment]
Just came here to request the same, but seems it isn't going to happen.
 - Using an empty bottle on a water source gives both a Bottle of Water and a TAN Dirty Water Bottle

**Comment by Darkhax** [comment]
I don't mind adding support for this, however it's not super easy to do. I believe the way you would support this, is to remove the dirty bottle from Tough As Nails, and then configure this mod to give a dirty bottle instead of the clean one. Of course, I don't know if that mod supports this or not. Currently this mod does not allow you to change the resulting item, however I have been plannning to add a recipe type system, which will allow you to change everything about this mod. For example you can say "When you right click on sand with a bottle, give sand in a bottle".

**Comment by Darkhax** [comment]
As of https://github.com/Darkhax-Minecraft/Thirsty-Bottles/commit/e74fd7b3ebdd384a0ac2175c84657980abda0b4a you can now configure the ID and the meta for the resulting item.
